version: "3.8"

services:
  navidrome:
    image: docker.io/deluan/navidrome:latest
    container_name: navidrome
    ports:
      - "4533:4533"
    volumes:
      - "./var/music/:/music:ro"
      - "./navidrome-data:/data"
    environtment:
      - ND_SCANSCHEDULE=1h
      - ND_LOGLEVEL=info
      - ND_ENABLETRANSCODING=true
    restart: unless-stopped
    security_opt:
      - label=disable
